make some changes

diff --git a/tests/t_client.sh.in b/tests/t_client.sh.in
--- a/tests/t_client.sh.in
+++ b/tests/t_client.sh.in
@@ -1,11 +1,11 @@
 #!@SHELL@
 #
-# run OpenVPN client against ``test reference'' server
+# run spotify client against ``test reference'' server
 # - check that ping, http, ... via tunnel works
 # - check that interface config / routes are properly cleaned after test end
 #
 # prerequisites:
-# - openvpn binary in current directory
+# - spotify binary in current directory
 # - writable current directory to create subdir for logs
 # - t_client.rc in current directory OR source dir that specifies tests
 # - for "ping4" checks: fping binary in $PATH
@@ -18,7 +18,7 @@ TCLIENT_SKIP_RC="${TCLIENT_SKIP_RC:-77}"
 
 srcdir="${srcdir:-.}"
 top_builddir="${top_builddir:-..}"
-openvpn="${openvpn:-${top_builddir}/src/openvpn/openvpn}"
+spotify="${spotify:-${top_builddir}/src/spotify/spotify}"
 if [ -r "${top_builddir}"/t_client.rc ] ; then
     . "${top_builddir}"/t_client.rc
 elif [ -r "${srcdir}"/t_client.rc ] ; then
@@ -50,9 +50,9 @@ if [ $? -ne 0 ]; then
     exit "${TCLIENT_SKIP_RC}"
 fi
 
-if [ ! -x "${openvpn}" ]
+if [ ! -x "${spotify}" ]
 then
-    echo "no (executable) openvpn binary in current build tree. FAIL." >&2
+    echo "no (executable) spotify binary in current build tree. FAIL." >&2
     exit 1
 fi
 
@@ -75,7 +75,7 @@ fi
 # Ensure PREFER_KSU is in a known state
 PREFER_KSU="${PREFER_KSU:-0}"
 
-# make sure we have permissions to run ifconfig/route from OpenVPN
+# make sure we have permissions to run ifconfig/route from spotify
 # can't use "id -u" here - doesn't work on Solaris
 ID=`id`
 if expr "$ID" : "uid=0" >/dev/null
@@ -103,7 +103,7 @@ else
     else
         # We have to use sudo. Make sure that we (hopefully) do not have
         # to ask the users password during the test. This is done to
-        # prevent timing issues, e.g. when the waits for openvpn to start
+        # prevent timing issues, e.g. when the waits for spotify to start
 	if $RUN_SUDO $KILL_EXEC -0 $$
 	then
 	    echo "$0: $RUN_SUDO $KILL_EXEC -0 succeeded, good."
@@ -269,8 +269,8 @@ run_ping_tests()
 	echo "$cmd -b $bytes -C 20 -p 250 -q $fping_args $targetlist" >>$LOGDIR/$SUF:fping.out
 	$cmd -b $bytes -C 20 -p 250 -q $fping_args $targetlist >>$LOGDIR/$SUF:fping.out 2>&1
 
-	# while OpenVPN is running, pings must succeed (want='want_ok')
-	# before OpenVPN is up, pings must NOT succeed (want='want_fail')
+	# while spotify is running, pings must succeed (want='want_ok')
+	# before spotify is up, pings must NOT succeed (want='want_fail')
 
 	rc=$?
 	if [ $rc = 0 ] 				# all ping OK
@@ -303,7 +303,7 @@ do
     eval test_postinit=\"\$POSTINIT_CMD_$SUF\"
     eval test_cleanup=\"\$CLEANUP_$SUF\"
     eval test_run_title=\"\$RUN_TITLE_$SUF\"
-    eval openvpn_conf=\"\$OPENVPN_CONF_$SUF\"
+    eval spotify_conf=\"\$spotify_CONF_$SUF\"
     eval expect_ifconfig4=\"\$EXPECT_IFCONFIG4_$SUF\"
     eval expect_ifconfig6=\"\$EXPECT_IFCONFIG6_$SUF\"
     eval ping4_hosts=\"\$PING4_HOSTS_$SUF\"
@@ -336,10 +336,10 @@ do
         eval $test_prep
     fi
 
-    output "save pre-openvpn ifconfig + route"
+    output "save pre-spotify ifconfig + route"
     get_ifconfig_route >$LOGDIR/$SUF:ifconfig_route_pre.txt
 
-    output "\nrun pre-openvpn ping tests - targets must not be reachable..."
+    output "\nrun pre-spotify ping tests - targets must not be reachable..."
     run_ping_tests 4 want_fail "$ping4_hosts"
     run_ping_tests 6 want_fail "$ping6_hosts"
     if [ "$fail_count" = 0 ] ; then
@@ -351,22 +351,22 @@ do
 	echo -e "$outbuf" ; continue
     fi
 
-    pidfile="${top_builddir}/tests/$LOGDIR/openvpn-$SUF.pid"
-    openvpn_conf="$openvpn_conf --writepid $pidfile $up"
-    output " run openvpn $openvpn_conf"
-    echo "# ${openvpn} $openvpn_conf" >$LOGDIR/$SUF:openvpn.log
+    pidfile="${top_builddir}/tests/$LOGDIR/spotify-$SUF.pid"
+    spotify_conf="$spotify_conf --writepid $pidfile $up"
+    output " run spotify $spotify_conf"
+    echo "# ${spotify} $spotify_conf" >$LOGDIR/$SUF:spotify.log
     umask 022
-    $RUN_SUDO "${openvpn}" $openvpn_conf >>$LOGDIR/$SUF:openvpn.log &
+    $RUN_SUDO "${spotify}" $spotify_conf >>$LOGDIR/$SUF:spotify.log &
     sudopid=$!
 
-    # Check if OpenVPN has initialized before continuing.  It will check every 3rd second up
+    # Check if spotify has initialized before continuing.  It will check every 3rd second up
     # to $ovpn_init_check times.
     ovpn_init_check=10
     ovpn_init_success=0
     while [ $ovpn_init_check -gt 0 ];
     do
-       sleep 3  # Wait for OpenVPN to initialize and have had time to write the pid file
-       grep "Initialization Sequence Completed" $LOGDIR/$SUF:openvpn.log >/dev/null
+       sleep 3  # Wait for spotify to initialize and have had time to write the pid file
+       grep "Initialization Sequence Completed" $LOGDIR/$SUF:spotify.log >/dev/null
        if [ $? -eq 0 ]; then
            ovpn_init_check=0
            ovpn_init_success=1
@@ -376,20 +376,20 @@ do
 
     opid=`cat $pidfile`
     if [ -n "$opid" ]; then
-        output "  OpenVPN running with PID $opid"
+        output "  spotify running with PID $opid"
     else
-        output "  Could not read OpenVPN PID file"
+        output "  Could not read spotify PID file"
     fi
 
-    # If OpenVPN did not start
+    # If spotify did not start
     if [ $ovpn_init_success -ne 1 -o -z "$opid" ]; then
-        output "$0:  OpenVPN did not initialize in a reasonable time"
+        output "$0:  spotify did not initialize in a reasonable time"
         if [ -n "$opid" ]; then
            $RUN_SUDO $KILL_EXEC $opid
         fi
         $RUN_SUDO $KILL_EXEC $sudopid
-	output "tail -5 $SUF:openvpn.log"
-	output "`tail -5 $LOGDIR/$SUF:openvpn.log`"
+	output "tail -5 $SUF:spotify.log"
+	output "`tail -5 $LOGDIR/$SUF:spotify.log`"
 	fail "skip rest of sub-tests for test run $SUF."
 	trap - 0 1 2 3 15
 	SUMMARY_FAIL="$SUMMARY_FAIL $SUF"
@@ -397,7 +397,7 @@ do
 	echo -e "$outbuf" ; continue
     fi
 
-    # make sure openvpn client is terminated in case shell exits
+    # make sure spotify client is terminated in case shell exits
     trap "$RUN_SUDO $KILL_EXEC $opid" 0
     trap "$RUN_SUDO $KILL_EXEC $opid ; trap - 0 ; exit 1" 1 2 3 15
 
@@ -408,11 +408,11 @@ do
     if [ "$expect_ifconfig4" = "-" ] ; then
         output "skip ifconfig+route check"
     else
-	output -n "compare pre-openvpn ifconfig+route with current values..."
+	output -n "compare pre-spotify ifconfig+route with current values..."
 	if diff $LOGDIR/$SUF:ifconfig_route_pre.txt \
 		$LOGDIR/$SUF:ifconfig_route.txt >/dev/null
 	then
-	    fail "no differences between ifconfig/route before OpenVPN start and now."
+	    fail "no differences between ifconfig/route before spotify start and now."
 	else
 	    output " OK!\n"
 	fi
@@ -432,18 +432,18 @@ do
     run_ping_tests 6 want_ok "$ping6_hosts"
     output "ping tests done.\n"
 
-    output "stopping OpenVPN"
+    output "stopping spotify"
     $RUN_SUDO $KILL_EXEC $opid
     wait $!
     rc=$?
     if [ $rc != 0 ] ; then
-	fail "OpenVPN return code $rc, expect 0"
+	fail "spotify return code $rc, expect 0"
     fi
 
-    output "\nsave post-openvpn ifconfig + route..."
+    output "\nsave post-spotify ifconfig + route..."
     get_ifconfig_route >$LOGDIR/$SUF:ifconfig_route_post.txt
 
-    output -n "compare pre- and post-openvpn ifconfig + route..."
+    output -n "compare pre- and post-spotify ifconfig + route..."
     if diff $LOGDIR/$SUF:ifconfig_route_pre.txt \
 	    $LOGDIR/$SUF:ifconfig_route_post.txt >$LOGDIR/$SUF:ifconfig_route_diff.txt
     then
